Repository mixxxdj/website, pull requests merged in 2020-06, with the labels that each got.

#100 2.3 release announcement: Improve download link
  pages/news/2020-06-07-mixxx-2-3-beta-released.html
Labels: enhancement

#103 Unmute embedded videos, add controls and fix CSS
  static/css/custom.css
  static/js/video.js
Labels: bug

#102 New post about GSoC
  pages/news/2020-06-08-mixxx-GSoC-Coding-Begins.html
Labels: news

#107 Add code background to highlight front page "Open Source" section
  pages/index.html
  static/css/custom.css
  static/images/cover/code-bg.jpg
  templates/donate_paypal.html
Labels: enhancement

#104 pages/download: Make donation section more prominent
  pages/download.html
Labels: enhancement

#108 Fix text alignment
  pages/index.html
  pages/support.html
Labels: enhancement

#85 Release Mixxx 2.2.4
  pages/download.html
  pages/news/2020-06-11-Mixxx-2-2-4-released.html
Labels: release

#113 Switch to GitHub wiki
  pages/download.html
  pages/features.html
  pages/get-involved.html
  pages/index.html
  pages/news/2008-03-12-mixxx-at-cheap-as-chips-2008.html
  pages/news/2008-03-18-mixxx-in-google-summer-of-code-2008.html
  pages/news/2008-05-27-mixxx-1-6-0-beta-3-released.html
  pages/news/2008-06-21-progress-towards-1-6-0.html
  pages/news/2009-04-23-mixxx-1-7-0-beta1-released.html
  pages/news/2009-08-06-mixxx-1-7-0-released.html
  pages/news/2009-12-23-mixxx-18-preview.html
  pages/news/2010-03-18-mixxx-in-google-summer-of-code-2010.html
  pages/news/2010-06-27-turning-mixxx-blog-into-blog.html
  pages/news/2010-07-01-mixxx-1-8-0-beta-2-released.html
  pages/news/2010-10-05-mixxx-180-released.html
  pages/news/2012-03-16-mixxx-in-google-summer-of-code-2012.html
  pages/news/2013-04-08-calling-all-students-hack-on-mixxx-in-google-summer-of-code-2013.html
  pages/news/2015-04-29-mixxx-1-12-beta-released.html
  pages/news/2015-12-05-surprise-release-candidate-1.html
  pages/news/2015-12-30-announcing-mixxx-2-0.html
  pages/news/2018-04-16-mixxx-2-1-0-has-arrived.html
  pages/sitemap.xml
  pages/support.html
  plugins/page_context.py
  templates/footer.html
Labels: enhancement

#115 pages/news/2020-06-29-black-lives-matter: Remove duplicate BLM headline
  pages/news/2020-06-29-black-lives-matter.html
Labels: maintenance, news
